doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        # This is needed for 'fastest' see https://github.com/liuggio/fastest/issues/101
        dbname: '%env(DATABASE_NAME)'
        mapping_types:
            enum: string
        types:
            datetime: App\Doctrine\DBAL\Types\UTCDateTimeType
            datetimetz: App\Doctrine\DBAL\Types\UTCDateTimeType
            EnumLogLogin: App\Doctrine\DBAL\Types\EnumLogLoginType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity\'
                alias: App
