# See docs https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    serializer:
        enable_annotations: true
    csrf_protection: false
    php_errors:
        log: true
    router:
        strict_requirements: null
    cache:
        pools:
            app.version.cache:
                adapter: cache.adapter.apcu
