nelmio_api_doc:
    routes:
        path_patterns: # an array of regexps
            - ^/[a-z]
    documentation:
        info:
            title: Symfony Flex Backend
            description: REST API with Symfony Flex
            version: 1.0.0
