services:
    repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        shared: false

    App\Repository\HealthzRepository:
        parent: repository
        arguments: [ App\Entity\Healthz ]

    App\Repository\LogLoginFailureRepository:
        parent: repository
        arguments: [ App\Entity\LogLoginFailure ]

    App\Repository\LogLoginSuccessRepository:
        parent: repository
        arguments: [ App\Entity\LogLoginSuccess ]

    App\Repository\RequestLogRepository:
        parent: repository
        arguments: [ App\Entity\RequestLog ]

    App\Repository\RoleRepository:
        parent: repository
        arguments: [ App\Entity\Role ]

    App\Repository\UserGroupRepository:
        parent: repository
        arguments: [ App\Entity\UserGroup ]

    App\Repository\UserRepository:
        parent: repository
        arguments: [ App\Entity\User ]
        calls:
            - [ setLogger, [ '@logger'] ]
