services:
    repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        shared: false

    App\Repository\RoleRepository:
        parent: repository
        arguments: [ App\Entity\Role ]

    App\Repository\UserGroupRepository:
        parent: repository
        arguments: [ App\Entity\UserGroup ]

    App\Repository\UserRepository:
        parent: repository
        arguments: [ App\Entity\User ]
