security:
    # http://symfony.com/doc/current/cookbook/security/named_encoders.html
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [user_provider, api_key_user_provider]

        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider

        user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/auth/getToken$
            stateless: true
            anonymous: true
            json_login:
                check_path: /auth/getToken
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        root:
            pattern: ^/$
            stateless: true
            anonymous: true

        api:
            pattern: ^/
            stateless: true
            anonymous: true
            simple_preauth:
                authenticator: App\Security\ApiKeyAuthenticator
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    role_hierarchy:
        ROLE_API:   [ROLE_LOGGED]
        ROLE_USER:  [ROLE_LOGGED]
        ROLE_ADMIN: [ROLE_USER]
        ROLE_ROOT:  [ROLE_ADMIN]

    access_decision_manager:
        strategy: unanimous

