working_directory: src

exclude_patterns:
    - public/index.php
    - config/bundles.php

global_exclude_dirs:
    - bin
    - build
    - config
    - migrations
    - tests
    - var
    - vendor

pre_composer_script: |
    #!/bin/bash
    cp ./../.env.dist ./../.env.yml
