rules:
    composer.unfixed_dependency_version:
        enabled: false
    web.missing_favicon:
        enabled: false

exclude_patterns:
    - public/index.php
    - config/bundles.php
    - 'var/*'

global_exclude_dirs:
    - bin
    - build
    - config
    - migrations
    - tests
    - var
    - vendor

pre_composer_script: |
    #!/bin/bash
