php_version: 7.4

pre_composer_script: |
    #!/bin/bash
    sed -i -e 's/\/app\/secrets\/application.json/.\/secrets\/application.json/g' .env

global_exclude_dirs:
    - bin
    - build
    - config
    - migrations
    - tests
    - var
    - vendor

exclude_patterns:
    - tests/bootstrap_fastest.php
