language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 1

services:
  - mysql

php:
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - cp .env.travis .env
  - cp .env.travis .env.test

install:
  - composer install
  - make generate-jwt-keys

before_script:
  - php --version
  - php bin/console --version
  - vendor/bin/phpunit --version
  - php bin/check.php

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php vendor/bin/coveralls -v; fi
