language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 1

services:
  - mysql

php:
  - 7.1
  - 7.2
  - nightly

env:
  matrix:
    - USE_XDEBUG=true
    - USE_XDEBUG=false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly

before_install:
  - cp .env.travis .env
  - cp .env.travis .env.test

install:
  - composer install
  - make generate-jwt-keys

before_script:
  - if [[ ${USE_XDEBUG} == false ]]; then phpenv config-rm xdebug.ini; fi
  - php --version
  - php bin/console --version
  - vendor/bin/phpunit --version
  - vendor/bin/requirements-checker

script:
  - make run-tests

after_success:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" && ${USE_XDEBUG} == true ]]; then php vendor/bin/coveralls -v; fi

after_failure:
  - cat var/logs/*.log
