services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    test.App\Security\RolesService: '@App\Security\RolesService'
    test.App\Utils\Tests\Auth: '@App\Utils\Tests\Auth'
