name: PHP Composer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --no-progress
      env:
        APPLICATION_CONFIG: ./secrets/application_test.json

  psalm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --no-progress
      env:
        APPLICATION_CONFIG: ./secrets/application_test.json

    - name: Psalm
      run: make psalm

  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --no-progress
      env:
        APPLICATION_CONFIG: ./secrets/application_test.json

    - name: PhpStan
      run: make phpstan

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
